name: Update fork
on:
  schedule:
    - cron:  '*/6 * * * *'
jobs:
  updateFork:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: andrenatal/bergamot-translator-from
      - name: Reset the default branch with upstream changes
        run: |
          git remote add upstream https://github.com/andrenatal-bot/repo.git
          git fetch upstream master:upstream-master
          git reset --hard upstream-master
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}
          branch: upstream-changes
