name: Update fork
on:
  push:
    branches:
      - main
jobs:
  updateFork:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: andrenatal/bergamot-translator-from
      - name: Reset the default branch with upstream changes
        run: |
          git remote add upstream https://github.com/andrenatal-bot/bergamot-translator-from.git
          git fetch upstream main:upstream-main
          git reset --hard upstream-main
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}
          branch: upstream-changes
